config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Shawn Rice</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
  	<%= copyright_generator%></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The "Screaming into the Void" Blog</h1>
    <p class="lead blog-description">It's still ranting, but now it has a professional looking header.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
  <div class="blog-masthead">
    <div class="container">
      <nav class="nav blog-nav">
        <%= nav_helper 'nav-link', 'span' %>
  	    <%= login_helper 'nav-link' %>
      </nav>
    </div>
  </div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Stuff I say about the things that I see.</p>
  </div>
  
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://www.linkedin.com/in/shawn-r-systems-science"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://github.com/lQQ3"><%= fa_icon "github" %></a></li>
      <li><a href="https://en.wikipedia.org/wiki/Serious_game"><%= fa_icon "wikipedia-w" %></a></li>
      <li><a href="https://soundcloud.com/user-21997151/shawnrice_phillipmarlowe_thepa/s-jU2mZ"><%= fa_icon "soundcloud" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">

</div>

app/views/shared/_portfolio_footer.html.erb
  

  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <%= link_to "View All Portfolio Items", portfolios_path %> /
        <a href="#">Back to top</a>
      </p>
      <p>
      	<%= copyright_generator %>
      </p>
    </div>
  </footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio Examples</h1>
    <p class="lead text-muted">Hardware, OS and language agnostic, I am engrossed with logical machines of all variety. I work with computers and electronics not simply as an occupation, but rather as a life-long passion. Below you will find examples of my work.</p>
    <p>
      <%= link_to "Find Out More About Me", about_me_path, class: 'btn btn-primary' %>
      <%= link_to "My Blog", blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Systems Science - Data Modeling - Artificial Intelligence - Machine Learning - Deep Learning - Data/Computer Sciences - Privacy/Security Engineering - Full Stack Software Development - Systems Analysis</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Shawn Rice</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>